# Generated by Django 4.1.7 on 2023-03-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Games', models.CharField(default=0, max_length=255)),
                ('Wins', models.CharField(default=0, max_length=255)),
                ('Loses', models.CharField(default=0, max_length=255)),
            ],
        ),
    ]
