# Generated by Django 4.1.7 on 2023-03-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_category_masters_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masters',
            name='cat',
        ),
    ]
