# Generated by Django 4.1.7 on 2023-03-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0004_remove_masters_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='masters',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chess.category'),
        ),
    ]
