# Generated by Django 4.1.7 on 2023-03-24 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0005_masters_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masters',
            name='cat',
            field=models.ForeignKey(null='man', on_delete=django.db.models.deletion.PROTECT, to='chess.category'),
        ),
    ]
